PREFIX ski: <http://example.org/ski#>

SELECT ?person ?firstName ?lastName ?email ?phone
WHERE {
  ?person a ski:Person ;
          ski:firstName ?firstName ;
          ski:lastName ?lastName ;
          ski:email ?email ;
          ski:phone ?phone .
}
