PREFIX ski: <http://example.org/ski#>

SELECT ?appointment ?startTime ?endTime ?appointmentID ?price ?paid ?amountPaidOnline
WHERE {
  ?appointment a ski:Appointment ;
               ski:startTime ?startTime ;
               ski:endTime ?endTime ;
               ski:appointmentID ?appointmentID ;
               ski:hasPayment ?payment .

  ?payment ski:price ?price ;
           ski:isPaid ?paid ;
           ski:amountPaidOnline ?amountPaidOnline .
}
