PREFIX ski: <http://example.org/ski#>

SELECT ?day (COUNT(*) AS ?count)
WHERE {
  ?appointment a ski:Appointment ;
               ski:startTime ?startTime .
  BIND(REPLACE(?startTime, " [0-9]{2}:[0-9]{2}$", "") AS ?day)
}
GROUP BY ?day
ORDER BY ?day
